robot_model:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
    gains:
      joint0: {p : 0.5 , i : 0.1 , d : 0.0 , i_clamp : 0.0}
      joint1: {p : 0.5 , i : 0.1 , d : 0.0 , i_clamp : 0.0}
      joint2: {p : 0.5 , i : 0.1 , d : 0.0 , i_clamp : 0.0}
      joint3: {p : 0.5 , i : 0.1 , d : 0.0 , i_clamp : 0.0}
      joint4: {p : 0.5 , i : 0.1 , d : 0.0 , i_clamp : 0.0}

