controller_list:
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      []
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - joint0
      - joint1
      - joint2
      - joint3
      - joint4
initial:  # Define initial robot poses.
  - group: arm
    pose: init